sensor:
  #--------------------------------------------------------------------------------------------
  - name: "Aduro H2 Smoke Temperature"
    unique_id: sensor.aduro_smoketemperature
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['smoke_temp'] is defined %}
        {{ value_json['STATUS']['smoke_temp'] | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_smoketemperature') }}
      {% endif %}
    unit_of_measurement: "째C"
    device_class: temperature

  - name: "Aduro H2 Shaft Temperature"
    unique_id: sensor.aduro_shafttemperature
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['shaft_temp'] is defined %}
        {{ value_json['STATUS']['shaft_temp'] | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_shafttemperature') }}
      {% endif %}
    unit_of_measurement: "째C"
    device_class: temperature

  - name: "Aduro H2 Power kW"
    unique_id: sensor.aduro_power_kw
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['power_kw'] is defined %}
        {{ value_json['STATUS']['power_kw'] | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_power_kw') }}
      {% endif %}
    unit_of_measurement: "kW"
    #device_class: energy

  - name: "Aduro H2 Power W"
    unique_id: sensor.aduro_power_w
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['power_kw'] is defined %}
        {{ (value_json['STATUS']['power_kw'] | float * 1000) | round(1) }}
      {% else %}
        {{ states('sensor.aduro_power_w') }}
      {% endif %}
    unit_of_measurement: "W"
    #device_class: energy

  - name: "Aduro H2 State"
    unique_id: sensor.aduro_state
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['state'] is defined %}
        {{ value_json['STATUS']['state'] | float | round(0) }}
      {% else %}
        {{ states('sensor.aduro_state') }}
      {% endif %}

  - name: "Aduro H2 Substate"
    unique_id: sensor.aduro_substate
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['substate'] is defined %}
        {{ value_json['STATUS']['substate'] | float | round(0) }}
      {% else %}
        {{ states('sensor.aduro_substate') }}
      {% endif %}

  - name: "Aduro H2 Oxygen"
    unique_id: sensor.aduro_oxygen
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['oxygen'] is defined %}
        {{ value_json['STATUS']['oxygen'] | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_oxygen') }}
      {% endif %}
    unit_of_measurement: "ppm"

  - name: "Aduro H2 Consumption Day"
    unique_id: sensor.aduro_consumption_day
    state_topic: "aduro_h2/consumption_data"
    state_class: measurement
    unit_of_measurement: "kg"
    value_template: >-
      {% if value_json is defined and value_json.CONSUMPTION is defined and value_json.CONSUMPTION.Day is defined %}
        {{ value_json.CONSUMPTION.Day | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_consumption_day') }}
      {% endif %}
    #device_class: energy

  - name: "Aduro H2 Consumption Yesterday"
    unique_id: sensor.aduro_consumption_yesterday
    state_topic: "aduro_h2/consumption_data"
    state_class: measurement
    unit_of_measurement: "kg"
    value_template: >-
      {% if value_json is defined and value_json.CONSUMPTION is defined and value_json.CONSUMPTION.Yesterday is defined %}
        {{ value_json.CONSUMPTION.Yesterday | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_consumption_yesterday') }}
      {% endif %}
    #device_class: energy

  - name: "Aduro H2 Consumption Month"
    unique_id: sensor.aduro_consumption_month
    state_topic: "aduro_h2/consumption_data"
    state_class: measurement
    unit_of_measurement: "kg"
    value_template: >-
      {% if value_json is defined and value_json.CONSUMPTION is defined and value_json.CONSUMPTION.Month is defined %}
        {{ value_json.CONSUMPTION.Month | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_consumption_month') }}
      {% endif %}
    #device_class: energy

  - name: "Aduro H2 Consumption Year"
    unique_id: sensor.aduro_consumption_year
    state_topic: "aduro_h2/consumption_data"
    state_class: measurement
    unit_of_measurement: "kg"
    value_template: >-
      {% if value_json is defined and value_json.CONSUMPTION is defined and value_json.CONSUMPTION.Year is defined %}
        {{ value_json.CONSUMPTION.Year | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_consumption_year') }}
      {% endif %}
    #device_class: energy

  - name: "Aduro H2 Consumption Total2"
    unique_id: sensor.aduro_consumption_total_2
    state_topic: "aduro_h2/status"
    state_class: measurement
    unit_of_measurement: "kg"
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['consumption_total'] is defined %}
        {{ value_json['STATUS']['consumption_total'] | float | round(0) }}
      {% else %}
        {{ states('sensor.aduro_consumption_total_2') }}
      {% endif %}
    #device_class: energy

  - name: "Aduro H2 Consumption Total"
    unique_id: sensor.aduro_consumption_total
    state_topic: "aduro_h2/status"
    state_class: measurement
    unit_of_measurement: "kg"
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['consumption_total'] is defined %}
        {{ (value_json['STATUS']['consumption_total'] | float + 500) | round(0) }}
      {% else %}
        {{ states('sensor.aduro_consumption_total') }}
      {% endif %}
    #device_class: energy

  - name: "Aduro H2 Stove Serial"
    unique_id: sensor.aduro_stove_serial
    state_topic: "aduro_h2/discovery"
    value_template: >-
      {% if value_json is defined and value_json.DISCOVERY is defined and value_json.DISCOVERY.StoveSerial is defined %}
        {{ value_json.DISCOVERY.StoveSerial }}
      {% else %}
        {{ states('sensor.aduro_stove_serial') }}
      {% endif %}

  - name: "Aduro H2 Stove IP"
    unique_id: sensor.aduro_stove_ip
    state_topic: "aduro_h2/discovery"
    value_template: >-
      {% if value_json is defined and value_json.DISCOVERY is defined and value_json.DISCOVERY.StoveIP is defined %}
        {{ value_json.DISCOVERY.StoveIP }}
      {% else %}
        {{ states('sensor.aduro_stove_ip') }}
      {% endif %}

  - name: "Aduro H2 Stove Heatlevel"
    unique_id: sensor.aduro_stove_heatlevel
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['regulation.fixed_power'] is defined %}
        {%   if (value_json['STATUS']['regulation.fixed_power']|float) | round(0) == 10 %}
          1
        {% elif (value_json['STATUS']['regulation.fixed_power']|float) | round(0) == 50 %}
          2
        {% elif (value_json['STATUS']['regulation.fixed_power']|float) | round(0) == 100 %}
          3
        {% endif %}
      {% else %}
        {{ states('sensor.aduro_stove_heatlevel') }}
      {% endif %}

  #-----------------------------------------------------------------------------------------------
  - name: "Aduro H2 Boiler Temp"
    unique_id: sensor.aduro_boilertemp
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['boiler_temp'] is defined %}
        {{ value_json['STATUS']['boiler_temp'] | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_boilertemp') }}
      {% endif %}
    unit_of_measurement: "째C"
    device_class: temperature

  - name: "Aduro H2 Boiler Ref"
    unique_id: sensor.aduro_boilerref
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['boiler_ref'] is defined %}
        {{ value_json['STATUS']['boiler_ref'] | float | round(1) }}
      {% else %}
        {{ states('sensor.aduro_boilerref') }}
      {% endif %}
    unit_of_measurement: "째C"
    device_class: temperature

  - name: "Aduro H2 Operation mode"
    unique_id: sensor.aduro_operation_mode
    state_topic: "aduro_h2/status"
    state_class: measurement
    value_template: >-
      {% if value_json is defined and value_json['STATUS'] is defined and value_json['STATUS']['operation_mode'] is defined %}
        {{ value_json['STATUS']['operation_mode'] | float | round(0) }}
      {% else %}
        {{ states('sensor.aduro_operation_mode') }}
      {% endif %}
